"""add_insulin_records_table

Revision ID: 62a2fa6e0e3f
Revises: 8cf7c70a1e74
Create Date: 2025-09-21 15:57:32.994849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62a2fa6e0e3f'
down_revision: Union[str, None] = '8cf7c70a1e74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('insulin_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('insulin_type', sa.Enum('FOOD', 'CORRECTION', name='insulintype'), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_insulin_records_date'), 'insulin_records', ['date'], unique=False)
    op.create_index(op.f('ix_insulin_records_id'), 'insulin_records', ['id'], unique=False)
    op.create_index(op.f('ix_insulin_records_user_id'), 'insulin_records', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_insulin_records_user_id'), table_name='insulin_records')
    op.drop_index(op.f('ix_insulin_records_id'), table_name='insulin_records')
    op.drop_index(op.f('ix_insulin_records_date'), table_name='insulin_records')
    op.drop_table('insulin_records')
    # ### end Alembic commands ###
