"""add_insulin_records_table

Revision ID: 62a2fa6e0e3f
Revises: 8cf7c70a1e74
Create Date: 2025-09-21 15:57:32.994849

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = "62a2fa6e0e3f"
down_revision: Union[str, None] = "8cf7c70a1e74"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Создаем ENUM тип только если он не существует
    op.execute("""
        DO $$ BEGIN
            CREATE TYPE insulintype AS ENUM ('FOOD', 'CORRECTION');
        EXCEPTION
            WHEN duplicate_object THEN null;
        END $$;
    """)

    # Создаем таблицу только если она не существует
    op.execute("""
        CREATE TABLE IF NOT EXISTS insulin_records (
            id SERIAL NOT NULL,
            user_id INTEGER NOT NULL,
            date DATE NOT NULL,
            insulin_type insulintype NOT NULL,
            amount FLOAT NOT NULL,
            created_at TIMESTAMP WITHOUT TIME ZONE,
            PRIMARY KEY (id),
            FOREIGN KEY(user_id) REFERENCES users (id)
        )
    """)

    # Создаем индексы только если они не существуют
    op.execute("CREATE INDEX IF NOT EXISTS ix_insulin_records_date ON insulin_records (date)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_insulin_records_id ON insulin_records (id)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_insulin_records_user_id ON insulin_records (user_id)")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Удаляем индексы только если они существуют
    op.execute("DROP INDEX IF EXISTS ix_insulin_records_user_id")
    op.execute("DROP INDEX IF EXISTS ix_insulin_records_id")
    op.execute("DROP INDEX IF EXISTS ix_insulin_records_date")

    # Удаляем таблицу только если она существует
    op.execute("DROP TABLE IF EXISTS insulin_records")

    # Удаляем ENUM тип только если он существует
    op.execute("DROP TYPE IF EXISTS insulintype")
    # ### end Alembic commands ###
